-- Add missing columns to food_logs table
ALTER TABLE food_logs 
ADD COLUMN IF NOT EXISTS food_id VARCHAR(50),
ADD COLUMN IF NOT EXISTS food_name VARCHAR(255),
ADD COLUMN IF NOT EXISTS carbs_g DECIMAL,
ADD COLUMN IF NOT EXISTS sugar_g DECIMAL,
ADD COLUMN IF NOT EXISTS protein_g DECIMAL,
ADD COLUMN IF NOT EXISTS fat_g DECIMAL,
ADD COLUMN IF NOT EXISTS fiber_g DECIMAL,
ADD COLUMN IF NOT EXISTS calories INTEGER,
ADD COLUMN IF NOT EXISTS glucose_impact_score DECIMAL,
ADD COLUMN IF NOT EXISTS spike_height DECIMAL;

-- Add missing columns to dexcom_tokens_egvs
ALTER TABLE dexcom_tokens
ADD COLUMN IF NOT EXISTS event_source VARCHAR(50) DEFAULT 'CGM',
ADD COLUMN IF NOT EXISTS food_id VARCHAR(50),
ADD COLUMN IF NOT EXISTS food_name VARCHAR(255);
