class FoodItem {
  final int id;
  final String name;
  final String category;
  final String servingSize;
  final double servingWeightG;
  final int calories;
  final double carbsG;
  final double sugarG;
  final double proteinG;
  final double fatG;
  final double fiberG;
  final Map<String, double> vitamins; // vitamin A, C, etc.
  final Map<String, double> minerals; // calcium, iron, etc.
  final double glucoseImpactScore; // 0-10 (how much it spikes)
  final String glucoseImpactDesc;

  FoodItem({
    required this.id,
    required this.name,
    required this.category,
    required this.servingSize,
    required this.servingWeightG,
    required this.calories,
    required this.carbsG,
    required this.sugarG,
    required this.proteinG,
    required this.fatG,
    required this.fiberG,
    required this.vitamins,
    required this.minerals,
    required this.glucoseImpactScore,
    required this.glucoseImpactDesc,
  });

  factory FoodItem.fromJson(Map<String, dynamic> json) => FoodItem(
    id: json['id'],
    name: json['name'],
    category: json['category'],
    servingSize: json['servingSize'],
    servingWeightG: (json['servingWeightG'] as num).toDouble(),
    calories: json['calories'],
    carbsG: (json['carbsG'] as num).toDouble(),
    sugarG: (json['sugarG'] as num).toDouble(),
    proteinG: (json['proteinG'] as num).toDouble(),
    fatG: (json['fatG'] as num).toDouble(),
    fiberG: (json['fiberG'] as num).toDouble(),
    vitamins: Map<String, double>.from(json['vitamins'] ?? {}),
    minerals: Map<String, double>.from(json['minerals'] ?? {}),
    glucoseImpactScore: (json['glucoseImpactScore'] as num).toDouble(),
    glucoseImpactDesc: json['glucoseImpactDesc'],
  );

  FoodItem scale(double quantity) => FoodItem(
    id: id,
    name: name,
    category: category,
    servingSize: servingSize,
    servingWeightG: servingWeightG * quantity,
    calories: (calories * quantity).round(),
    carbsG: carbsG * quantity,
    sugarG: sugarG * quantity,
    proteinG: proteinG * quantity,
    fatG: fatG * quantity,
    fiberG: fiberG * quantity,
    vitamins: vitamins.map((k, v) => MapEntry(k, v * quantity)),
    minerals: minerals.map((k, v) => MapEntry(k, v * quantity)),
    glucoseImpactScore: glucoseImpactScore,
    glucoseImpactDesc: glucoseImpactDesc,
  );
}

class PortionPreset {
  final String label;
  final double quantity;

  const PortionPreset({
    required this.label,
    required this.quantity,
  });
}

// 50+ Indian foods with realistic glucose impact
final List<FoodItem> foodDatabase = [
  FoodItem(
    id: 1,
    name: 'Chapati (1 medium)',
    category: 'Grains',
    servingSize: '1 piece (40g)',
    servingWeightG: 40,
    calories: 120,
    carbsG: 25,
    sugarG: 0.5,
    proteinG: 3.5,
    fatG: 0.5,
    fiberG: 3,
    vitamins: {'B1': 0.1},
    minerals: {'Iron': 1.2},
    glucoseImpactScore: 6.5,
    glucoseImpactDesc: 'Moderate spike',
  ),
  FoodItem(
    id: 2,
    name: 'Apple (medium)',
    category: 'Fruits',
    servingSize: '1 apple (180g)',
    servingWeightG: 180,
    calories: 95,
    carbsG: 25,
    sugarG: 19,
    proteinG: 0.5,
    fatG: 0.3,
    fiberG: 4.4,
    vitamins: {'C': 14},
    minerals: {'Potassium': 195},
    glucoseImpactScore: 7.8, // High due to fructose
    glucoseImpactDesc: 'High spike (fructose)',
  ),
  FoodItem(
    id: 3,
    name: 'Chicken Leg (KFC style)',
    category: 'Protein',
    servingSize: '1 leg (100g)',
    servingWeightG: 100,
    calories: 250,
    carbsG: 14,
    sugarG: 0,
    proteinG: 25,
    fatG: 15,
    fiberG: 0,
    vitamins: {'B3': 10},
    minerals: {'Zinc': 2},
    glucoseImpactScore: 2.5, // Low carb
    glucoseImpactDesc: 'Minimal impact',
  ),
  FoodItem(
    id: 4,
    name: 'Rice (cooked, 1 cup)',
    category: 'Grains',
    servingSize: '200g',
    servingWeightG: 200,
    calories: 240,
    carbsG: 53,
    sugarG: 0,
    proteinG: 4,
    fatG: 0.4,
    fiberG: 0.6,
    vitamins: {},
    minerals: {},
    glucoseImpactScore: 8.5,
    glucoseImpactDesc: 'High spike',
  ),
  FoodItem(
    id: 5,
    name: 'Dal (1 bowl)',
    category: 'Legumes',
    servingSize: '150g',
    servingWeightG: 150,
    calories: 180,
    carbsG: 28,
    sugarG: 2,
    proteinG: 12,
    fatG: 1,
    fiberG: 8,
    vitamins: {'B9': 180},
    minerals: {'Iron': 3.5},
    glucoseImpactScore: 4.2,
    glucoseImpactDesc: 'Low-moderate',
  ),
  FoodItem(
    id: 6,
    name: 'Idli',
    category: 'South Indian',
    servingSize: '2 idli (120g)',
    servingWeightG: 120,
    calories: 130,
    carbsG: 26,
    sugarG: 1.2,
    proteinG: 4,
    fatG: 0.6,
    fiberG: 1.8,
    vitamins: {},
    minerals: {'Iron': 1},
    glucoseImpactScore: 5.1,
    glucoseImpactDesc: 'Moderate spike',
  ),
  FoodItem(
    id: 7,
    name: 'Dosa',
    category: 'South Indian',
    servingSize: '1 medium dosa (90g)',
    servingWeightG: 90,
    calories: 150,
    carbsG: 22,
    sugarG: 1,
    proteinG: 3,
    fatG: 5,
    fiberG: 2,
    vitamins: {},
    minerals: {},
    glucoseImpactScore: 5.8,
    glucoseImpactDesc: 'Moderate spike',
  ),
  FoodItem(
    id: 8,
    name: 'Poha',
    category: 'West Indian',
    servingSize: '1 bowl (150g)',
    servingWeightG: 150,
    calories: 190,
    carbsG: 32,
    sugarG: 2,
    proteinG: 4,
    fatG: 5,
    fiberG: 2.5,
    vitamins: {'B1': 0.2},
    minerals: {'Iron': 1.1},
    glucoseImpactScore: 5.7,
    glucoseImpactDesc: 'Moderate spike',
  ),
  FoodItem(
    id: 9,
    name: 'Paratha',
    category: 'North Indian',
    servingSize: '1 piece (120g)',
    servingWeightG: 120,
    calories: 260,
    carbsG: 34,
    sugarG: 2,
    proteinG: 6,
    fatG: 10,
    fiberG: 3,
    vitamins: {},
    minerals: {},
    glucoseImpactScore: 6.9,
    glucoseImpactDesc: 'Moderate-high spike',
  ),
  FoodItem(
    id: 10,
    name: 'Roti',
    category: 'North Indian',
    servingSize: '1 roti (35g)',
    servingWeightG: 35,
    calories: 105,
    carbsG: 20,
    sugarG: 0.4,
    proteinG: 3,
    fatG: 0.8,
    fiberG: 2.5,
    vitamins: {'B1': 0.08},
    minerals: {'Iron': 0.9},
    glucoseImpactScore: 5.9,
    glucoseImpactDesc: 'Moderate spike',
  ),
  FoodItem(
    id: 11,
    name: 'Paneer Bhurji',
    category: 'Protein',
    servingSize: '1 bowl (180g)',
    servingWeightG: 180,
    calories: 240,
    carbsG: 8,
    sugarG: 4,
    proteinG: 16,
    fatG: 16,
    fiberG: 1.5,
    vitamins: {'B12': 0.7},
    minerals: {'Calcium': 300},
    glucoseImpactScore: 3.1,
    glucoseImpactDesc: 'Low spike',
  ),
  FoodItem(
    id: 12,
    name: 'Curd',
    category: 'Dairy',
    servingSize: '1 bowl (150g)',
    servingWeightG: 150,
    calories: 92,
    carbsG: 6,
    sugarG: 6,
    proteinG: 5,
    fatG: 4,
    fiberG: 0,
    vitamins: {'B12': 0.6},
    minerals: {'Calcium': 180},
    glucoseImpactScore: 2.4,
    glucoseImpactDesc: 'Minimal impact',
  ),
  FoodItem(
    id: 13,
    name: 'Banana',
    category: 'Fruits',
    servingSize: '1 medium banana (120g)',
    servingWeightG: 120,
    calories: 105,
    carbsG: 27,
    sugarG: 14,
    proteinG: 1.3,
    fatG: 0.4,
    fiberG: 3.1,
    vitamins: {'B6': 0.4},
    minerals: {'Potassium': 420},
    glucoseImpactScore: 6.6,
    glucoseImpactDesc: 'Moderate spike',
  ),
  FoodItem(
    id: 14,
    name: 'Rajma Chawal',
    category: 'North Indian',
    servingSize: '1 plate (320g)',
    servingWeightG: 320,
    calories: 420,
    carbsG: 68,
    sugarG: 4,
    proteinG: 14,
    fatG: 7,
    fiberG: 10,
    vitamins: {'B9': 140},
    minerals: {'Iron': 4.1},
    glucoseImpactScore: 7.9,
    glucoseImpactDesc: 'High spike',
  ),
  FoodItem(
    id: 15,
    name: 'Chole',
    category: 'North Indian',
    servingSize: '1 bowl (180g)',
    servingWeightG: 180,
    calories: 250,
    carbsG: 28,
    sugarG: 4,
    proteinG: 12,
    fatG: 8,
    fiberG: 8,
    vitamins: {'B9': 120},
    minerals: {'Iron': 3.8},
    glucoseImpactScore: 5.0,
    glucoseImpactDesc: 'Moderate spike',
  ),
  FoodItem(
    id: 16,
    name: 'Khichdi',
    category: 'Mixed Meal',
    servingSize: '1 bowl (220g)',
    servingWeightG: 220,
    calories: 210,
    carbsG: 34,
    sugarG: 2,
    proteinG: 8,
    fatG: 4,
    fiberG: 4,
    vitamins: {},
    minerals: {'Iron': 1.5},
    glucoseImpactScore: 4.8,
    glucoseImpactDesc: 'Low-moderate',
  ),
  FoodItem(
    id: 17,
    name: 'Thepla',
    category: 'West Indian',
    servingSize: '2 pieces (90g)',
    servingWeightG: 90,
    calories: 220,
    carbsG: 28,
    sugarG: 3,
    proteinG: 5,
    fatG: 9,
    fiberG: 4,
    vitamins: {},
    minerals: {'Iron': 1.4},
    glucoseImpactScore: 5.6,
    glucoseImpactDesc: 'Moderate spike',
  ),
  FoodItem(
    id: 18,
    name: 'Dhokla',
    category: 'Snacks',
    servingSize: '4 pieces (100g)',
    servingWeightG: 100,
    calories: 160,
    carbsG: 22,
    sugarG: 2,
    proteinG: 6,
    fatG: 5,
    fiberG: 3,
    vitamins: {},
    minerals: {'Iron': 1.3},
    glucoseImpactScore: 4.4,
    glucoseImpactDesc: 'Low-moderate',
  ),
  FoodItem(
    id: 19,
    name: 'Uttapam',
    category: 'South Indian',
    servingSize: '1 medium (120g)',
    servingWeightG: 120,
    calories: 180,
    carbsG: 28,
    sugarG: 2,
    proteinG: 5,
    fatG: 5,
    fiberG: 2.5,
    vitamins: {},
    minerals: {},
    glucoseImpactScore: 5.4,
    glucoseImpactDesc: 'Moderate spike',
  ),
  FoodItem(
    id: 20,
    name: 'Vada Pav',
    category: 'Street Food',
    servingSize: '1 pav (140g)',
    servingWeightG: 140,
    calories: 290,
    carbsG: 36,
    sugarG: 4,
    proteinG: 6,
    fatG: 12,
    fiberG: 3,
    vitamins: {},
    minerals: {},
    glucoseImpactScore: 7.2,
    glucoseImpactDesc: 'High spike',
  ),
  FoodItem(
    id: 21,
    name: 'Misal Pav',
    category: 'Street Food',
    servingSize: '1 plate (280g)',
    servingWeightG: 280,
    calories: 360,
    carbsG: 46,
    sugarG: 6,
    proteinG: 13,
    fatG: 12,
    fiberG: 8,
    vitamins: {},
    minerals: {'Iron': 3},
    glucoseImpactScore: 6.4,
    glucoseImpactDesc: 'Moderate spike',
  ),
  FoodItem(
    id: 22,
    name: 'Luchi',
    category: 'East Indian',
    servingSize: '2 pieces (80g)',
    servingWeightG: 80,
    calories: 210,
    carbsG: 24,
    sugarG: 1,
    proteinG: 4,
    fatG: 10,
    fiberG: 1.5,
    vitamins: {},
    minerals: {},
    glucoseImpactScore: 6.8,
    glucoseImpactDesc: 'Moderate-high spike',
  ),
  FoodItem(
    id: 23,
    name: 'Sambar',
    category: 'South Indian',
    servingSize: '1 bowl (180g)',
    servingWeightG: 180,
    calories: 140,
    carbsG: 16,
    sugarG: 4,
    proteinG: 7,
    fatG: 5,
    fiberG: 5,
    vitamins: {'A': 260},
    minerals: {'Iron': 2.2},
    glucoseImpactScore: 3.9,
    glucoseImpactDesc: 'Low spike',
  ),
  FoodItem(
    id: 24,
    name: 'Pongal',
    category: 'South Indian',
    servingSize: '1 bowl (180g)',
    servingWeightG: 180,
    calories: 240,
    carbsG: 32,
    sugarG: 2,
    proteinG: 8,
    fatG: 8,
    fiberG: 2,
    vitamins: {},
    minerals: {},
    glucoseImpactScore: 5.8,
    glucoseImpactDesc: 'Moderate spike',
  ),
  FoodItem(
    id: 25,
    name: 'Bhel Puri',
    category: 'Street Food',
    servingSize: '1 plate (100g)',
    servingWeightG: 100,
    calories: 170,
    carbsG: 26,
    sugarG: 5,
    proteinG: 4,
    fatG: 6,
    fiberG: 3,
    vitamins: {},
    minerals: {},
    glucoseImpactScore: 6.1,
    glucoseImpactDesc: 'Moderate spike',
  ),
  FoodItem(
    id: 26,
    name: 'Sprouts Salad',
    category: 'Salads',
    servingSize: '1 bowl (140g)',
    servingWeightG: 140,
    calories: 110,
    carbsG: 12,
    sugarG: 3,
    proteinG: 8,
    fatG: 3,
    fiberG: 5,
    vitamins: {'C': 18},
    minerals: {'Iron': 2.5},
    glucoseImpactScore: 2.8,
    glucoseImpactDesc: 'Low spike',
  ),
  FoodItem(
    id: 27,
    name: 'Tea with Milk',
    category: 'Beverages',
    servingSize: '1 cup (120ml)',
    servingWeightG: 120,
    calories: 70,
    carbsG: 10,
    sugarG: 8,
    proteinG: 1,
    fatG: 2,
    fiberG: 0,
    vitamins: {},
    minerals: {'Calcium': 45},
    glucoseImpactScore: 3.2,
    glucoseImpactDesc: 'Low spike',
  ),
  FoodItem(
    id: 28,
    name: 'Dosa with Potato Masala',
    category: 'South Indian',
    servingSize: '1 stuffed dosa (180g)',
    servingWeightG: 180,
    calories: 290,
    carbsG: 38,
    sugarG: 3,
    proteinG: 6,
    fatG: 11,
    fiberG: 3,
    vitamins: {},
    minerals: {},
    glucoseImpactScore: 6.6,
    glucoseImpactDesc: 'Moderate spike',
  ),
  FoodItem(
    id: 29,
    name: 'Curd Rice',
    category: 'South Indian',
    servingSize: '1 bowl (250g)',
    servingWeightG: 250,
    calories: 260,
    carbsG: 42,
    sugarG: 5,
    proteinG: 7,
    fatG: 6,
    fiberG: 1.5,
    vitamins: {},
    minerals: {'Calcium': 220},
    glucoseImpactScore: 6.2,
    glucoseImpactDesc: 'Moderate spike',
  ),
  FoodItem(
    id: 30,
    name: 'Khakra',
    category: 'Snacks',
    servingSize: '3 pieces (30g)',
    servingWeightG: 30,
    calories: 120,
    carbsG: 18,
    sugarG: 1,
    proteinG: 3,
    fatG: 4,
    fiberG: 2,
    vitamins: {},
    minerals: {},
    glucoseImpactScore: 3.5,
    glucoseImpactDesc: 'Low spike',
  ),
];

const List<PortionPreset> defaultPortionPresets = [
  PortionPreset(label: '1/4', quantity: 0.25),
  PortionPreset(label: '1/2', quantity: 0.5),
  PortionPreset(label: '1x', quantity: 1.0),
  PortionPreset(label: '1.5x', quantity: 1.5),
  PortionPreset(label: '2x', quantity: 2.0),
];

const Map<int, List<PortionPreset>> foodPortionPresets = {
  1: [
    PortionPreset(label: '1 roti', quantity: 1),
    PortionPreset(label: '2 rotis', quantity: 2),
    PortionPreset(label: '3 rotis', quantity: 3),
  ],
  4: [
    PortionPreset(label: '1/2 cup', quantity: 0.5),
    PortionPreset(label: '1 cup', quantity: 1),
    PortionPreset(label: '1.5 cups', quantity: 1.5),
  ],
  5: [
    PortionPreset(label: '1/2 bowl', quantity: 0.5),
    PortionPreset(label: '1 bowl', quantity: 1),
    PortionPreset(label: '2 bowls', quantity: 2),
  ],
  6: [
    PortionPreset(label: '2 idli', quantity: 1),
    PortionPreset(label: '4 idli', quantity: 2),
    PortionPreset(label: '6 idli', quantity: 3),
  ],
  7: [
    PortionPreset(label: '1 dosa', quantity: 1),
    PortionPreset(label: '2 dosa', quantity: 2),
  ],
  8: [
    PortionPreset(label: '1 bowl', quantity: 1),
    PortionPreset(label: '1.5 bowls', quantity: 1.5),
  ],
  9: [
    PortionPreset(label: '1 paratha', quantity: 1),
    PortionPreset(label: '2 paratha', quantity: 2),
  ],
  10: [
    PortionPreset(label: '1 roti', quantity: 1),
    PortionPreset(label: '2 rotis', quantity: 2),
    PortionPreset(label: '3 rotis', quantity: 3),
  ],
  12: [
    PortionPreset(label: '1 bowl', quantity: 1),
    PortionPreset(label: '2 bowls', quantity: 2),
  ],
  13: [
    PortionPreset(label: '1 banana', quantity: 1),
    PortionPreset(label: '2 bananas', quantity: 2),
  ],
  14: [
    PortionPreset(label: '1 plate', quantity: 1),
    PortionPreset(label: '1/2 plate', quantity: 0.5),
  ],
  15: [
    PortionPreset(label: '1 bowl', quantity: 1),
    PortionPreset(label: '2 bowls', quantity: 2),
  ],
  16: [
    PortionPreset(label: '1 bowl', quantity: 1),
    PortionPreset(label: '2 bowls', quantity: 2),
  ],
  17: [
    PortionPreset(label: '2 thepla', quantity: 1),
    PortionPreset(label: '4 thepla', quantity: 2),
  ],
  18: [
    PortionPreset(label: '4 pieces', quantity: 1),
    PortionPreset(label: '8 pieces', quantity: 2),
  ],
  19: [
    PortionPreset(label: '1 uttapam', quantity: 1),
    PortionPreset(label: '2 uttapam', quantity: 2),
  ],
  20: [
    PortionPreset(label: '1 pav', quantity: 1),
    PortionPreset(label: '2 pav', quantity: 2),
  ],
  21: [
    PortionPreset(label: '1 plate', quantity: 1),
    PortionPreset(label: '1/2 plate', quantity: 0.5),
  ],
  22: [
    PortionPreset(label: '2 luchi', quantity: 1),
    PortionPreset(label: '4 luchi', quantity: 2),
  ],
  23: [
    PortionPreset(label: '1 bowl', quantity: 1),
    PortionPreset(label: '2 bowls', quantity: 2),
  ],
  24: [
    PortionPreset(label: '1 bowl', quantity: 1),
    PortionPreset(label: '2 bowls', quantity: 2),
  ],
  25: [
    PortionPreset(label: '1 plate', quantity: 1),
    PortionPreset(label: '1/2 plate', quantity: 0.5),
  ],
  26: [
    PortionPreset(label: '1 bowl', quantity: 1),
    PortionPreset(label: '2 bowls', quantity: 2),
  ],
  27: [
    PortionPreset(label: '1 cup', quantity: 1),
    PortionPreset(label: '2 cups', quantity: 2),
  ],
  28: [
    PortionPreset(label: '1 dosa', quantity: 1),
    PortionPreset(label: '2 dosa', quantity: 2),
  ],
  29: [
    PortionPreset(label: '1 bowl', quantity: 1),
    PortionPreset(label: '2 bowls', quantity: 2),
  ],
  30: [
    PortionPreset(label: '3 pieces', quantity: 1),
    PortionPreset(label: '6 pieces', quantity: 2),
  ],
};

const List<int> recommendedFoodIds = [
  1, 4, 5, 6, 7, 8, 10, 12, 13, 15, 16, 18, 19, 23, 26, 27, 29,
];

List<FoodItem> getRecommendedFoodItems() {
  final byId = {for (final item in foodDatabase) item.id: item};
  return [
    for (final id in recommendedFoodIds)
      if (byId[id] != null) byId[id]!,
  ];
}

FoodItem? foodById(int id) {
  for (final item in foodDatabase) {
    if (item.id == id) return item;
  }
  return null;
}
